DESIGN_NAME: top
VERILOG_FILES:
- dir::rtl/top.v
- dir::rtl/delay.v
- dir::rtl/flash_loader.v
- dir::rtl/memory_controller.v
- dir::rtl/spi_master.v
- dir::rtl/K_ADDER.v
- dir::rtl/K_ALU.v
- dir::rtl/K_DECODER.v
- dir::rtl/K_PC.v
- dir::rtl/K_REGS.v
- dir::rtl/KAMP_top.v
- dir::rtl/memory.v
FP_CORE_UTIL: 71.0244
PDK: ihp-sg13g2
FP_SIZING: relative
PDN_CORE_RING: True
PDN_CORE_RING_VWIDTH: 4
PDN_CORE_RING_HWIDTH: 4
PDN_CORE_RING_VOFFSET: 1
PDN_CORE_RING_HOFFSET: 1
PDN_CORE_RING_VSPACING: 2
PDN_CORE_RING_HSPACING: 2
PDN_VWIDTH: 3
PDN_VPITCH: 38
PDN_VSPACING: 2
PDN_VOFFSET: 20
FALLBACK_SDC: dir::sdc/KAMP_ihp.sdc
PNR_SDC_FILE: dir::sdc/KAMP_ihp.sdc
SIGNOFF_SDC_FILE: dir::sdc/KAMP_ihp.sdc
LEFT_MARGIN_MULT: 25
RIGHT_MARGIN_MULT: 25
BOTTOM_MARGIN_MULT: 3
TOP_MARGIN_MULT: 3
CLOCK_PORT: clk_i