create_clock -name CLK -period 20 [get_ports clk_i]
set_clock_uncertainty 0.005 CLK

set_output_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports flash_MOSI_o]
set_output_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports flash_SCK_o]
set_output_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports flash_NSS_o]
set_output_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports flash_MOSI_o]
set_output_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports flash_SCK_o]
set_output_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports flash_NSS_o]

set_output_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports {port_o[3]}]
set_output_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports {port_o[2]}]
set_output_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports {port_o[1]}]
set_output_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports {port_o[0]}]
set_output_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports {port_o[3]}]
set_output_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports {port_o[2]}]
set_output_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports {port_o[1]}]
set_output_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports {port_o[0]}]

set_output_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports {port_dir_o[3]}]
set_output_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports {port_dir_o[2]}]
set_output_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports {port_dir_o[1]}]
set_output_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports {port_dir_o[0]}]
set_output_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports {port_dir_o[3]}]
set_output_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports {port_dir_o[2]}]
set_output_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports {port_dir_o[1]}]
set_output_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports {port_dir_o[0]}]

set_input_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports {port_i[0]}]
set_input_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports {port_i[1]}]
set_input_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports {port_i[2]}]
set_input_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports {port_i[3]}]
set_input_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports {port_i[0]}]
set_input_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports {port_i[1]}]
set_input_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports {port_i[2]}]
set_input_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports {port_i[3]}]

set_input_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports cpu_en_i]
set_input_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports int_i]
set_input_delay -clock [get_clocks CLK] -add_delay -min 0 [get_ports flash_MISO_i]
set_input_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports cpu_en_i]
set_input_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports int_i]
set_input_delay -clock [get_clocks CLK] -add_delay -max 5 [get_ports flash_MISO_i]
